// Rock Roofing — operative form definitions (seed set).
// Built verbatim from Rock's real form exports. Forms can also be created/edited
// in the in-app Form Builder; these are the defaults. Field types: section,
// note (read-only text), shorttext, longtext, date, single, multi, photos,
// members (Team Member picker), signature.

export const CATEGORIES = [
  { id: 'company', label: 'Company Information', desc: 'Policies, insurances & standard documents' },
  { id: 'guidance', label: 'Operative Guidance Documents', desc: 'How-to guides & best practice' },
  { id: 'project', label: 'Project Forms', desc: 'Site diaries, reports & handovers' },
]

const dailySiteDiary = {
  id: "daily-site-diary",
  category: 'project',
  title: "Daily Site Diary - Operatives",
  description: "Operatives Daily Site Diary",
  fields: [
    { id: "s_1", type: "section", label: "General Information" },
    { id: "f_2", type: "date", label: "Site Diary Date", help: "Insert the date for which this Daily Site Diary applies", required: true },
    { id: "f_3", type: "members", label: "Insert your name", help: "Please select your name as the person completing the site diary", required: true },
    { id: "f_4", type: "members", label: "Personnel on site working on behalf of Rock", help: "Select all of the personnel working on site today. Multiple selections should be made if it is more than one person working on the project.", required: true },
    { id: "f_5", type: "multi", label: "Weather conditions", help: "Multiple choices possible. Check wind conditions whenever applicable.", options: ["Sunny, extremely hot", "Sunny and clear", "Cloudy / Overcast", "Rain showers", "Light but persistent rain", "Torrential rain and/or hail", "Somewhat windy", "Medium to strong wind", "Extremely strong wind", "Sunny, but cold and icy", "Misty, cold and icy", "Light snowfall", "Snowstorm / Blizzard"] },
    { id: "f_6", type: "multi", label: "Site conditions", help: "Please check the boxes that best describe the condition of the site. Multiple options can be selected.", options: ["Dry and clean - Works can proceed as planned.", "Somewhat wet - Works can be done.", "Wet - Some works possible but overall difficult.", "Very wet - No works can be done!", "Frozen (dry) - Slow progress possible.", "Snow cover - No works can be done!", "Very strong wind - Work extremely difficult!", "Other trades or others' materials on roof area - limited working space, works delayed.", "Debris or waste on roof area - works delayed until roof area is cleared.", "Roof area unsecure. H&S hazard present - DO NOT WORK!", "Site closed by Client / Site Management - No works can be done!"] },
    { id: "s_7", type: "section", label: "Daily Management Call" },
    { id: "f_8", type: "single", label: "Have you had your daily call with the Rock Roofing Contracts Manager?", required: true, options: ["Yes", "No"] },
    { id: "s_9", type: "section", label: "Variations" },
    { id: "f_10", type: "single", label: "Have you identified any Variations from the Contract Works?", required: true, options: ["Yes - I will call a Rock Roofing Manager now to discuss", "No"] },
    { id: "s_11", type: "section", label: "Materials" },
    { id: "f_12", type: "single", label: "Are there any materials that you need to ensure works can progress efficiently?", required: true, options: ["Yes - I will call / message Rock Roofing Management now", "No - I have everything I need for the next week minimum"] },
    { id: "f_13", type: "single", label: "Is all safety equipment available on site?", required: true, options: ["Yes", "No - please proceed to the next question"] },
    { id: "f_14", type: "shorttext", label: "Please specify what safety equipment is missing from site" },
    { id: "s_15", type: "section", label: "Delay and Disruption" },
    { id: "f_16", type: "single", label: "Have you experienced anything that has or will cause you delay?", required: true, options: ["Yes - I will raise a separate Issue Form now", "No"] },
    { id: "s_17", type: "section", label: "We only accept ABSOLUTE SAFETY: Zero Accidents" },
    { id: "f_18", type: "single", label: "Have all operatives digitally signed the latest copy of the RAMS? See RAMS in Project's FONN folder to check.", help: "Raise with Rock Roofing Management immediately if there are new operatives who haven't digitally signed onto the RAMS. No works can be carried out by the new installer until Rock Roofng Management have electronically signed our RAMS.", required: true, options: ["Yes", "No - I have instructed all operatives who haven't signed the RAMS to not work on site until they have digitally signed the RAMS"] },
    { id: "f_19", type: "single", label: "Do the RAMS still reflect site conditions?", help: "If site conditions have changed, stop works until RAMS have been updated by the Contracts Manager. Raise with Rock Roofing Management immediately.", required: true, options: ["Yes", "No - I have instructed everyone to stop works until the RAMS have been updated and digitally signed by all operatives"] },
    { id: "f_20", type: "multi", label: "Please select which options best describe any H&S issues encountered.", help: "Multiple options can be selected. If no H&S concerns found on site, select no H&S concerns. If any H&S concerns identified, an issue must be raised identifying and describing the H&S concern that needs resolution.", options: ["No H&S concerns", "Inadequate H&S communication with site management", "Bad housekeeping / badly stored materials", "Use of ladders", "Inadequate lifting equipment", "Malfunctioning electric power tools", "Manual handling", "Insufficient or inappropriate edge protection", "Unsafe plant equipment", "No internal scaffold or fall protection (staircase, roof lights, penetrations, etc.)", "Inadequate welfare facilities", "Inadequate PPE", "Slips, trips and falls", "Exposed or dangerously located live services", "Potential fire hazard", "Hazard coming from other trades", "Waste and/or hazardous waste on work area", "Bad weather conditions", "Access to site and works area has changed or isn't safe", "Proximity to the public"] },
    { id: "f_21", type: "single", label: "MANDATORY - Have we considered weather conditions when securing both loose and fixed materials?", help: "Consider up and coming weather conditions when securing both fixed and unfixed materials to prevent materials being blown off the roof / away from stored location.", required: true, options: ["Yes - have ensured all fixed and unfixed materials are secure with no risk of  blowing off the roof or unnecessary water ingress"] },
    { id: "f_22", type: "single", label: "Have you identified any H&S concerns?", required: true, options: ["Yes - I will raise a separate issue form now", "No"] },
    { id: "s_23", type: "section", label: "We are QUALITY OBSESSED: Zero Defects" },
    { id: "f_24", type: "longtext", label: "Are there other trades working on/in our works area? Describe what trades are working on our roof / in proximity to our cladding works area highlighting any concerns that you have.", required: true },
    { id: "f_25", type: "single", label: "Have you identified any quality concerns?", required: true, options: ["Yes - I will complete a separate issue form now", "No"] },
    { id: "f_26", type: "single", label: "Do you need to complete a Works Area Handover (WAH) form? See below for when required.", required: true, options: ["Yes - I will complete a WAH form now", "No"] },
    { id: "f_27", type: "note", label: "IMPORTANT! Works Area Handover form is needed every time when:" },
    { id: "f_28", type: "note", label: "1. When we are leaving site for longer than 2 days and there are still works to be completed on the project." },
    { id: "f_29", type: "note", label: "2. When any individual roof area / elevation has been completed on a project. e.g. 1 roof of 5 roof areas on a project has been completed." },
    { id: "f_30", type: "note", label: "3. When the project is completed in its entirety, including penetrations and perimeter details, etc.)" },
    { id: "s_31", type: "section", label: "Photos - works completed, site conditions, delay, quality, H&S issues." },
    { id: "f_32", type: "photos", label: "Insert PHOTOS of works completed, site conditions, delay, quality, H&S issues." },
    { id: "s_33", type: "section", label: "Approval" },
    { id: "f_34", type: "note", label: "I can confirm that the information I have provided is true and that I have completed all sections accurately and diligently" },
    { id: "f_35", type: "signature", label: "Signature" },
    { id: "f_36", type: "note", label: "Please \"SUBMIT & NOTIFY\" the Rock Roofing Contracts Manager who is responsible for this project." },
  ],
}

const dailyQualityInspection = {
  id: "daily-quality-inspection",
  category: 'project',
  title: "Daily Quality Inspection",
  description: "Daily quality inspection of installed roofing works.",
  fields: [
    { id: "s_1", type: "section", label: "Today's date" },
    { id: "f_2", type: "date", label: "Today's Date", required: true },
    { id: "f_3", type: "shorttext", label: "Subcontractor company on site" },
    { id: "s_4", type: "section", label: "Roof Area" },
    { id: "f_5", type: "shorttext", label: "Which roof area are you working on?", required: true },
    { id: "f_6", type: "shorttext", label: "Which part of the roof are you working on?", required: true },
    { id: "s_7", type: "section", label: "Area Build Up" },
    { id: "f_8", type: "photos", label: "Substrate - Insert photos of substrate clear of debris and showing suitable surface for fixing to." },
    { id: "f_9", type: "photos", label: "Membrane - Insert photos of membrane fully welded including any liquid PVC. Minimum 100 mm lap/ Minimum 100mm lap for side lap fixed." },
    { id: "f_10", type: "photos", label: "Protection Layer - Insert photos of any protection layer installed" },
    { id: "s_11", type: "section", label: "Perimeter Work" },
    { id: "f_12", type: "photos", label: "PVC Coated Metal / Restraining Bars - Insert photos of PVC coated metals fixed with the correct centres" },
    { id: "f_13", type: "photos", label: "PVC Coated Metal - Insert photos of 200mm butt straps correctly necked into the corners." },
    { id: "f_14", type: "photos", label: "Fleece Separation Layer - Insert Photos showing the install of the fleece separation layer to the parapet wall" },
    { id: "f_15", type: "photos", label: "Sidelap Fixing - Insert images showing the correct install of Sidelap Fixing (if applicable)" },
    { id: "f_16", type: "photos", label: "Corners - Insert photos of corners correctly installed" },
    { id: "s_17", type: "section", label: "Penetrations" },
    { id: "f_18", type: "photos", label: "Outlets - Insert photos of outlets installed correctly" },
    { id: "f_19", type: "photos", label: "Penetrations - Insert photos of penetrations correctly installed" },
    { id: "s_20", type: "section", label: "Other" },
    { id: "f_21", type: "photos", label: "Lightning Tabs - Insert photos of lightning tabs correctly installed" },
    { id: "f_22", type: "longtext", label: "Further Comments Box" },
  ],
}

const internalHSAudit = {
  id: "internal-hs-audit",
  category: 'project',
  title: "Internal H&S Audit",
  description: "Audit and inspection to ensure safe site working conditions and to document monitoring and actions taken to help maintain personnel safety. To be completed every time a manager attends a new site he/she has not been to for 1 week or more.",
  fields: [
    { id: "s_1", type: "section", label: "General Information" },
    { id: "f_2", type: "date", label: "Date on which this safety inspection took place", required: true },
    { id: "f_3", type: "members", label: "Your name" },
    { id: "f_4", type: "shorttext", label: "Subcontractor Company" },
    { id: "f_5", type: "multi", label: "Please confirm that you are on site during the completion of this H&S Audit.", help: "It is critical that this safety audit is completed on site and not done retrospectively. This audit should be completed with the appropriate time, diligence and accuracy that comes from completing on site with the situations and circumstances directly in front of you.", options: ["Yes"] },
    { id: "s_6", type: "section", label: "First Aider" },
    { id: "f_7", type: "single", label: "Is there a designated first aider present?", options: ["Yes", "No"] },
    { id: "s_8", type: "section", label: "Housekeeping" },
    { id: "f_9", type: "single", label: "Is the housekeeping to a good standard on the site?", options: ["Yes", "No"] },
    { id: "f_10", type: "single", label: "Is the site free from slips, trips and fall hazards?", options: ["Yes", "No"] },
    { id: "f_11", type: "photos", label: "Insert Photos of housekeeping", required: true },
    { id: "f_12", type: "longtext", label: "Describe rectification action taken to resolve" },
    { id: "s_13", type: "section", label: "Personal Protective Equipment (PPE)" },
    { id: "f_14", type: "single", label: "Are all persons on site wearing the appropriate PPE as prescribed in the RAMS?", options: ["Yes", "No"] },
    { id: "f_15", type: "photos", label: "Insert photos of Rock Roofing Operatives wearing / not wearing appropriate PPE", required: true },
    { id: "f_16", type: "longtext", label: "Describe rectification action taken to resolve" },
    { id: "s_17", type: "section", label: "Access and Fall Prevention Equipment" },
    { id: "f_18", type: "single", label: "Is all access and fall prevention equipment in good condition and has been inspected at regular intervals, certified for use?", options: ["Yes", "No"] },
    { id: "f_19", type: "photos", label: "*MANDATORY - Insert photos of access and fall prevention equipment including scaffold tags.", required: true },
    { id: "f_20", type: "longtext", label: "Describe rectification action taken to resolve" },
    { id: "s_21", type: "section", label: "Fire and Emergency Access Routes" },
    { id: "f_22", type: "single", label: "Are all fire escape and emergency routes and fire extinguishers clear and unobstructed?", options: ["Yes", "No"] },
    { id: "f_23", type: "longtext", label: "Describe rectification action taken to resolve" },
    { id: "f_24", type: "photos", label: "*MANDATORY - Insert photos of any access routes", required: true },
    { id: "s_25", type: "section", label: "Materials and Equipment Storage" },
    { id: "f_26", type: "single", label: "Are all materials and equipment stored safely?", options: ["Yes", "No"] },
    { id: "f_27", type: "photos", label: "*MANDATORY - Insert photos of any materials or equipment that is being stored", required: true },
    { id: "f_28", type: "longtext", label: "Describe rectification action taken to resolve" },
    { id: "s_29", type: "section", label: "Welfare" },
    { id: "f_30", type: "single", label: "Are welfare facilities adequate and clean?", options: ["Yes", "No"] },
    { id: "f_31", type: "photos", label: "*MANDATORY - Insert photos of welfare facilities", required: true },
    { id: "f_32", type: "longtext", label: "Describe rectification action taken to resolve" },
    { id: "s_33", type: "section", label: "Any other H&S issues" },
    { id: "f_34", type: "longtext", label: "Describe any other H&S issues encountered" },
    { id: "f_35", type: "longtext", label: "Check Correct operatives certification for using plant and equipment." },
    { id: "f_36", type: "photos", label: "Insert photos of any other H&S issues encountered" },
    { id: "f_37", type: "shorttext", label: "Describe rectification action taken to resolve" },
    { id: "f_38", type: "photos", label: "Insert photos to support any other H&S concerns raised" },
    { id: "s_39", type: "section", label: "Rectification" },
    { id: "f_40", type: "single", label: "Are there any questions from this Internal H&S Assessment where you answered \"No\" that still need to be resolved?", options: ["Yes - I have taken steps to ensure all workers are safe ceasing works where needed while we await resolution", "No"] },
    { id: "f_41", type: "single", label: "If you answered \"No\" to any of the questions located in the Internal H&S Assessment Section, have you raised these as a Task or Issue in this Internal H&S Assessment and assigned to the relevant person to address?", options: ["Yes", "N/A - There are no outstanding H&S concerns that need addressing"] },
    { id: "s_42", type: "section", label: "Approval" },
    { id: "f_43", type: "note", label: "I can confirm that the information I have provided is true and that I have completed all sections accurately and diligently" },
    { id: "f_44", type: "signature", label: "Signature" },
  ],
}

const waterIngress = {
  id: "water-ingress-report",
  category: 'project',
  title: "Water Ingress Report",
  description: "Water Ingress Report Form; completed in every instance where we have been advised by the customer that water has entered the building. This form is used to determine the cause of the water ingress, any remedy and who is responsible.",
  fields: [
    { id: "s_1", type: "section", label: "General Information" },
    { id: "f_2", type: "date", label: "Date on which the water ingress survey and assessment took place", help: "Insert the date that you went to site to survey the water ingress", required: true },
    { id: "f_3", type: "shorttext", label: "Your name", help: "Insert your name as the person who surveyed the project", required: true },
    { id: "f_4", type: "shorttext", label: "Who reported the water ingress?", help: "Insert the full name, job title, and company of the person who reported the water ingress.", required: true },
    { id: "f_5", type: "date", label: "What date was the water ingress reported?", help: "Insert the date on which the water ingress was reported to Rock.", required: true },
    { id: "s_6", type: "section", label: "Water Ingress" },
    { id: "f_7", type: "longtext", label: "What is the water ingress issue that has been reported to Rock?", help: "Describe in detail the water ingress issue that has been reported.", required: true },
    { id: "f_8", type: "shorttext", label: "What has happened as a result of the water ingress?", help: "Describe in detail what has occurred as a result of the water ingress. e.g. any damage, staining and the like.", required: true },
    { id: "f_9", type: "photos", label: "Insert photos of any damage caused by the water ingress", help: "Insert photos of any damage caused by the water ingress.", required: true },
    { id: "f_10", type: "single", label: "Have we established the cause of the water ingress?", options: ["Yes", "No", "Unable to determine the cause of the water ingress"] },
    { id: "f_11", type: "longtext", label: "What have we determined to be the cause of the water ingress?", help: "Describe in detail what the cause of the water ingress is.", required: true },
    { id: "f_12", type: "photos", label: "*MANDATORY - Insert photos of the cause of the water ingress", help: "Insert photos of the cause of the water ingress along with any other relevant images.", required: true },
    { id: "f_13", type: "single", label: "Who is responsible for the water ingress?", options: ["Rock", "The Main Contractor", "Other Trade Contractor", "Building End User / Building Maintenance Contractor", "Inconclusive"] },
    { id: "f_14", type: "multi", label: "Have you discussed your findings with a Rock Manager before leaving site?", options: ["Yes - Calling a RR Manager before leaving site is mandatory"] },
    { id: "s_15", type: "section", label: "The Solution" },
    { id: "f_16", type: "single", label: "Do we have a proposed solution to remedy and prevent any further water ingress?", options: ["Yes", "No", "TBC - further investigations / discussions needed"] },
    { id: "f_17", type: "longtext", label: "What further action is needed to remedy and prevent any further water ingress?", help: "Describe in detail the next steps including any solutions to prevent any further water ingress.", required: true },
    { id: "s_18", type: "section", label: "Approval" },
    { id: "f_19", type: "note", label: "I can confirm that the information I have provided is true and that I have completed all sections accurately and diligently" },
    { id: "f_20", type: "signature", label: "Signature" },
    { id: "f_21", type: "note", label: "Please \"SUBMIT & NOTIFY\" the Rock Contracts Manager who is responsible for this project." },
  ],
}

const startOnSite = {
  id: "start-on-site-checklist",
  category: 'project',
  title: "Start On Site Checklist",
  description: "Start on site checklist to be completed ideally at least three days before the first day of every project. This is a mandatory step to help drive our Zero Accidents objective helping to keep our team members and others safe during our works.",
  fields: [
    { id: "s_1", type: "section", label: "General Information" },
    { id: "f_2", type: "date", label: "Date on which this Start on Site Checklist applies", required: true },
    { id: "f_3", type: "members", label: "Your name", required: true },
    { id: "f_4", type: "members", label: "Operatives on site", help: "Insert the names of personnel working on behalf of Rock Roofing", required: true },
    { id: "f_5", type: "members", label: "Rock personnel on site", required: true },
    { id: "f_6", type: "single", label: "Has there been any internal works completed on the project?", required: true, options: ["Yes - I have raised an issue in FONN", "No"] },
    { id: "s_7", type: "section", label: "Labour Onboarding" },
    { id: "f_8", type: "single", label: "Do all operatives working on behalf of Rock have Rock branded Hi-Vis vests and relevant PPE?", required: true, options: ["Yes", "No "] },
    { id: "f_9", type: "single", label: "If there are roofing / cladding operatives on site without the correct Rock Roofing branded hi-vis vests and relevant PPE, have you raised this as a Task in this Start On Site Checklist and assigned a Rock Roofing manager to address?", required: true, options: ["Yes", "N/A - all operatives working on behalf of Rock roofing have Rock Roofing branded Hi-Vis vests"] },
    { id: "f_10", type: "single", label: "Is the labour aware that if they are paid hourly and will not be paid for arriving late or leaving early?", required: true, options: ["Yes", "No"] },
    { id: "f_11", type: "multi", label: "Has all of the labour been shown around the Rock Health and Safety Management system and Quality Management System (QMS)?", options: ["Health and Safety Policy", "Works Area Handover", "Daily Site Diary", "Daily Manager call between 8.00AM - 9.15AM", "Operative process steps and flow chart", "What to do in the event of an accident (Accident Book Form)", "Quality Management System"] },
    { id: "f_12", type: "multi", label: "Have you discussed with all labour the following?", options: ["Paid hourly, pro rata from day rate", "Site working hours", "Drawings, RAMS, Schedule, and Fixing Pattern location on FONN", "WhatsApp Project Group Chat", "Project sequencing", "No installers to be permitted onto Rock projects unless they have been pre-vetted by the office."] },
    { id: "s_13", type: "section", label: "We only accept ABSOLUTE SAFETY: Zero Accidents" },
    { id: "f_14", type: "single", label: "Have all installers that will arrive on site been included in the initial project labour review and vetted accordingly?", help: "All installers must have the appropriate training needed to carry out the task at hand. If an operative is not included on the labour review located on the RAMS, then Rock management must first ensure that the operative is on the H&S matrix and has sufficient training. No operative is permitted to start on site unless they have been fully vetted by Rock management.", required: true, options: ["Yes", "No - The unvetted operatives are not permitted to work on site until addressed by Rock management"] },
    { id: "f_15", type: "single", label: "If there are operatives not included on the labour review section in the RAMS, have you raised this as a Task in this Start On Site Checklist and assigned a Rock manager to address?", required: true, options: ["Yes ", "N/A"] },
    { id: "f_16", type: "single", label: "Have all operatives who will work on the project digitally signed the RAMS?", required: true, options: ["Yes", "No - The operatives who have not digitally signed the RAMS are not permitted to work on Rock sites until this has been addressed by Rock management. "] },
    { id: "f_17", type: "single", label: "If there are operatives not signed onto the RAMS, have you raised this as a Task in this Start on Site Checklist and assigned a Rock manager to address?", required: true, options: ["Yes", "N/A"] },
    { id: "f_18", type: "single", label: "Has the first aider on site been confirmed?", required: true, options: ["Yes", "No - We will not start work until the designated first aider has been confirmed"] },
    { id: "f_19", type: "single", label: "Is the working methodology, site environment, safety precautions and / or access to the roof the same as described in the RAMS?", required: true, options: ["Yes", "No - we have stopped works until the RAMS have been updated and signed by all operatives"] },
    { id: "f_20", type: "single", label: "If the working methodology, site environment, safety precautions and / or access to the roof has changed from the RAMS, have you raised this as a Task in this Start on Site Checklist and assigned to a Rock manager to address?", required: true, options: ["Yes", "N/A"] },
    { id: "f_21", type: "single", label: "Are there adequate welfare facilities on site?", required: true, options: ["Yes", "No"] },
    { id: "f_22", type: "single", label: "If the welfare facilities are inadequate, have you raised this as a Task in this Start on Site Checklist and assigned to a Rock manager to address?", required: true, options: ["Yes", "N/A"] },
    { id: "s_23", type: "section", label: "Internal H&S Assessment" },
    { id: "f_24", type: "single", label: "Is there a designated first aider present?", required: true, options: ["Yes", "No - we have stopped work until there is a first aider on site"] },
    { id: "f_25", type: "single", label: "Is the housekeeping to a good standard on the site?", required: true, options: ["Yes", "No - I have verbally notified the site manager that there is poor housekeeping that needs addressing"] },
    { id: "f_26", type: "single", label: "Are all persons on site wearing the appropriate PPE as prescribed in the RAMS", required: true, options: ["Yes", "No - I have advised anyone without the correct PPE that they are not permitted to work on site until they have the correct PPE to carry out the task at hand."] },
    { id: "f_27", type: "single", label: "Is all access and fall prevention equipment in good condition and has been inspected at regular intervals, certified for use?", required: true, options: ["Yes", "No - I have advised all operatives that the identified access equipment and fall prevention equipment is no longer permitted for use"] },
    { id: "f_28", type: "single", label: "Are all fire escape and emergency routes and fire extinguishers clear and unobstructed?", required: true, options: ["Yes", "No - I have verbally notified the site manager that this needs addressing immediately"] },
    { id: "f_29", type: "single", label: "Are all materials and equipment stored safely?", required: true, options: ["Yes", "No - we have made a safe exclusion zone while we ensure safe storage of materials and equipment"] },
    { id: "f_30", type: "single", label: "Is the site free from slips, trips and fall hazards?", help: "(trailing leads, areas where persons could fall, spills etc)", required: true, options: ["Yes", "No - We have notified the site manager of the area that needs clearing immediately and stopped work if the unclear area is not safely passable"] },
    { id: "f_31", type: "longtext", label: "Are there any other H&S issues / hazards on site with the potential to cause injury?", required: true },
    { id: "f_32", type: "longtext", label: "Have you already taken any corrective actions to address any questions in the Internal H&S Section where you have answered no?", required: true },
    { id: "f_33", type: "single", label: "If you answered No to any of the questions located in the Internal H&S Assessment Section, have you raised these as a Task in this Start On Site Checklist and assigned a Rock Roofing manager to address?", required: true, options: ["Yes", "N/A"] },
    { id: "s_34", type: "section", label: "Photos" },
    { id: "f_35", type: "photos", label: "*MANDATORY - Upload photos to support this Start on Site Checklist and evidence the site conditions and access.", help: "Insert photos of the site, site conditions, access equipment, perimeter handrailing, H&S concerns identified and anything else that will support this Start on Site Checklist.", required: true },
    { id: "s_36", type: "section", label: "In Person Customer Meeting" },
    { id: "f_37", type: "longtext", label: "What has been discussed about Programme and Sequencing?", required: true },
    { id: "f_38", type: "single", label: "Do we have the latest version of the project programme?", required: true, options: ["Yes", "No - To be Forwarded"] },
    { id: "f_39", type: "longtext", label: "What has been discussed with the customer about lifting?", required: true },
    { id: "f_40", type: "longtext", label: "Design / interface issues discussed?", required: true },
    { id: "f_41", type: "longtext", label: "Is there anything that may cause delays that has been discussed with the customer?", required: true },
    { id: "f_42", type: "longtext", label: "Anything else discussed with the customer?" },
    { id: "s_43", type: "section", label: "Approval" },
    { id: "f_44", type: "note", label: "I can confirm that the information I have provided is true and that I have completed all sections accurately and diligently" },
    { id: "f_45", type: "signature", label: "Signature" },
  ],
}

const ideasSuggestions = {
  id: "ideas-and-suggestions",
  category: 'project',
  title: "Ideas and Suggestions",
  description: "Form to present ideas and suggestions for improving your daily activities, Rock Roofing processes and systems, and to identify road blocks that you are currently facing.",
  fields: [
    { id: "s_1", type: "section", label: "General Information" },
    { id: "f_2", type: "note", label: "Rock Roofing are committed to ALWAYS FINDING A BETTER WAY. The main goal for anyone completing this form is the identification of issues that you face in your day to day roles. Once completed, this form is automatically forwarded to leaders in the team who will act on the issue you have identified. It does not matter if you do not have a solution for the problem. The main thing is that we are, as a team, all identifying the issues we are facing in our day to day roles so that we can look to make changes to remove and / or reduce the reoccurrence of the issues you are facing." },
    { id: "f_3", type: "date", label: "Today's date", required: true },
    { id: "s_4", type: "section", label: "The Problem" },
    { id: "f_5", type: "multi", label: "What category does the problem that you are facing predominantly fall under? You can select multiple options if applicable.", required: true, options: ["Management", "Post Contract and operations", "Pre-Contract and estimating", "Deliveries", "Design", "Customer satisfaction", "Processes", "Team members", "Quality", "Time inefficiencies", "Culture and values", "Organisation", "Health & Safety", "Pricing", "Other"] },
    { id: "f_6", type: "shorttext", label: "Name the problem", required: true },
    { id: "f_7", type: "longtext", label: "Describe in detail the problem, issue or roadblock that you are facing?", required: true },
    { id: "s_8", type: "section", label: "The Solution" },
    { id: "f_9", type: "single", label: "Do you have a proposed solution for the problem that you are facing?", options: ["Yes", "No"] },
    { id: "f_10", type: "longtext", label: "If you answered Yes above, describe in detail what potential solution you have to improve on the problem you have faced." },
  ],
}

const worksAreaHandover = {
  id: "works-area-handover",
  category: 'project',
  title: "Works Area Handover",
  description: "Works Area Handover to be completed if a roof area is finished / we leave site for more than 2 days / we finished the project entirely",
  fields: [
    { id: "s_1", type: "section", label: "General Information" },
    { id: "f_2", type: "date", label: "Date when we left site", help: "Insert the date on which we left site", required: true },
    { id: "f_3", type: "members", label: "Your name", help: "Insert your name", required: true },
    { id: "f_4", type: "members", label: "Operatives on site on the last day of the project", help: "Insert the names of the operatives who were on site on the last day of the installation during final checks" },
    { id: "s_5", type: "section", label: "Works Completed" },
    { id: "f_6", type: "single", label: "Are the project works completed in their entirety?", help: " IMPORTANT: answer \"Yes\" ONLY IF absolutely EVERYTHING IS DONE (roof, cladding, perimeter, capings, hatches, mansafe, lightning clips, protection layer, etc...) and we are NOT returning to this site anymore!", required: true, options: ["Yes", "No"] },
    { id: "f_7", type: "longtext", label: "Which works area/s are being handed over?", help: "Clearly describe the works areas being handed over. e.g. low level, high level, exposed roof area, terraces ground floor, roof area 1, all roof areas, North / South / East / West elevation complete etc.", required: true },
    { id: "f_8", type: "longtext", label: "Describe in detail the works being handed over", help: "Describe the works being handover.", required: true },
    { id: "f_9", type: "longtext", label: "Describe in detail any contracted works that are still to complete.", help: " Leave blank if all works are complete" },
    { id: "f_10", type: "longtext", label: "If there are still outstanding contracted works, what is the reason we are unable to complete?", help: "Describe the reason why we are unable to complete. e.g. plywood to parapet not installed by others, metal deck not installed by others, Awaiting more materials, scaffold on roof etc. Leave blank if all works are complete." },
    { id: "f_11", type: "shorttext", label: "Describe any supply only materials we have left on site and who we have left them with.", help: "For example: protection layer, lightning clips, AOV, actuator, electric/electronic control units, roof lights, outlets, cappings for other to install, etc. Leave blank if not applicable." },
    { id: "f_12", type: "multi", label: "Have you inserted photos of the works completed and detailed in this WAH?", help: "Inserting photos are a mandatory requirement for every WAH. More photos the better including of overall works completed, outstanding items that require completing, areas which are holding us up, and close up photos of detailing.", options: ["Yes - I have inserted photos of works completed in relation to this WAH and also photos of areas where we are unable to complete"] },
    { id: "f_13", type: "photos", label: "*MANDATORY - Insert photos showing completed project. Include overall photos and photos of specific detailing to demonstrate the quality of the works complete.", required: true },
    { id: "s_14", type: "section", label: "We are QUALITY OBSESSED: Zero Defects" },
    { id: "f_15", type: "single", label: "Have you checked the roof / cladding works are defect free?", required: true, options: ["Yes", "No - I have reported to the Rock Roofing Contracts Manager identified quality issues"] },
    { id: "s_16", type: "section", label: "We are PROACTIVE: Housekeeping" },
    { id: "f_17", type: "single", label: "Is the roof / cladding works area clear of waste and debris?", options: ["Yes", "No", "N/A - leaving site"] },
    { id: "f_18", type: "single", label: "Are materials adequately weighed down / secured?", options: ["Yes", "No", "N/A - leaving site"] },
    { id: "f_19", type: "longtext", label: "Describe in detail any materials we have left on the project.", help: "Include exact quantities and types of materials. Leave blank if NA" },
    { id: "f_20", type: "shorttext", label: "Where have materials been safely stored on the project?", help: "Describe specifically where materials have been left on the project" },
    { id: "f_21", type: "photos", label: "Insert a photo of any materials left on the project" },
    { id: "f_22", type: "shorttext", label: "Who from the customer's site team has agreed the location of where materials have been left?" },
    { id: "f_23", type: "single", label: "Do Rock management need to arrange for materials to be collected from site??", options: ["Yes", "No - there are no more materials left on this project", "Current project materials are required for other roof areas"] },
    { id: "f_24", type: "shorttext", label: "Is there any tool that needs to be off hired? If yes, please describe in detail.", required: true },
    { id: "f_25", type: "shorttext", label: "Have any materials that need to be collected from site been raised as a Task in this site diary and assigned it to your Rock manager to address?" },
    { id: "s_26", type: "section", label: "Plant and Equipment" },
    { id: "f_27", type: "single", label: "Is there any plant or equipment to be off-hired?", required: true, options: ["Yes", "No"] },
    { id: "f_28", type: "shorttext", label: "Which Rock Roofing manager have you notified of any plant or equipment that needs off-hiring?" },
    { id: "f_29", type: "longtext", label: "Describe the plant and equipment that needs off-hiring" },
    { id: "s_30", type: "section", label: "Notes" },
    { id: "f_31", type: "note", label: "Main Contractor / Customer Acceptance - *No response within 3 days of receiving this Works Area Handover (WAH) confirms acceptance of Rock's completed works." },
    { id: "s_32", type: "section", label: "Approval" },
    { id: "f_33", type: "note", label: "I  confirm that the information I have provided is true and that I have completed all sections accurately and diligently" },
    { id: "f_34", type: "signature", label: "Signature" },
    { id: "f_35", type: "note", label: "Please \"SUBMIT & NOTIFY\" the Rock Roofing Operations Manager who is responsible for this project." },
  ],
}

const preStart = {
  id: "pre-start-notification",
  category: 'project',
  title: "Pre-Start Notification",
  description: "Pre-Start Notification to advise the customer of all materials being delivered, works being carried out and what needs to be ready for us prior to us arriving on site. To be sent prior to every visit on site.",
  fields: [
    { id: "s_1", type: "section", label: "The Works" },
    { id: "f_2", type: "date", label: "Confirmed start / return date", help: "Insert the date we are starting works on site or the date on which we are returning to site", required: true },
    { id: "f_3", type: "shorttext", label: "Who requested us to return to site?", help: "Insert the full name of the person who requested us to return to site", required: true },
    { id: "f_4", type: "shorttext", label: "What is the email address of the person who requested us to return to site? i.e. who does this pre-start notification need to be sent to?", required: true },
    { id: "f_5", type: "single", label: "How was the start on site / return to site date communicated?", options: ["Email", "Phone Call", "Instant Messaging"] },
    { id: "f_6", type: "date", label: "On what date were we given a confirmed start on site / return to site date?", help: "Insert the date on which the customer's site team gave us a confirmed start on site / return to site date.", required: true },
    { id: "f_7", type: "shorttext", label: "Visit Number", help: "Insert what number visit this is.", required: true },
    { id: "f_8", type: "longtext", label: "Describe the works that have been agreed to be carried out in this visit.", help: "Describe in detail the works that have been agreed to be carried out in this visit. Be as descriptive and detailed as possible.", required: true },
    { id: "s_9", type: "section", label: "Deliveries, Offloading, and Lifting" },
    { id: "f_10", type: "shorttext", label: "What materials are being delivered, on what date and on what type of vehicle?", required: true },
    { id: "f_11", type: "multi", label: "How have materials been agreed to be safely offloaded from delivery vehicles?", required: true, options: ["Telehandler", "Vehicle with Moffit", "Crane", "Pallet Truck", "Vehicle with tail lift", "Ancillaries or fixings only, mechanical offloading N/A"] },
    { id: "f_12", type: "single", label: "Who is responsible for offloading?", required: true, options: ["The Main Contractor / Customer", "Rock Roofing Ltd"] },
    { id: "f_13", type: "single", label: "What type of mechanical lifting has been agreed for vertical distribution?", required: true, options: ["Crane", "Telehandler", "Goods Hoist", "MEWP"] },
    { id: "f_14", type: "single", label: "Who is responsible for vertical distribution / lifting?", required: true, options: ["The Main Contractor / Customer", "Rock Roofing Ltd"] },
    { id: "f_15", type: "single", label: "Has a laydown area been agreed or are materials being lifted directly onto the roof / offloaded to work area?", options: ["Materials stored at ground level and lifted to roof / walls as required", "Materials being lifted directly onto the roof"] },
    { id: "s_16", type: "section", label: "Access" },
    { id: "f_17", type: "single", label: "What is the agreed access to the roof / walls? ***MEWPs are not a permitted means of roof access.", required: true, options: ["Haki Staricase", "Scaffold", "Ladder", "MEWP"] },
    { id: "f_18", type: "multi", label: "What means of collective fall protection are we using? ***Rock Roofing do not work off harnesses", required: true, options: ["Perimeter Scaffold", "Perimeter Handrail", "Parapet wall with a height greater than 950mm"] },
    { id: "f_19", type: "single", label: "Who is responsible for providing safe access equipment and collective fall protection measures?", options: ["The Main Contractor / The Customer", "Rock Roofing Ltd"] },
    { id: "s_20", type: "section", label: "Works by Others" },
    { id: "f_21", type: "longtext", label: "What works are required to be completed by others prior to our visit to site?", required: true },
    { id: "s_22", type: "section", label: "Design" },
    { id: "f_23", type: "longtext", label: "Describe any items relating to interface, design or approval that need resolving prior to our arrival at site.", required: true },
    { id: "f_24", type: "note", label: "*We will be unable to start on site if there are any outstanding design items still to be approved. All costs associated with any down time as a result of unapproved design will be deemed recoverable until all outstanding design has been signed off." },
    { id: "s_25", type: "section", label: "H&S" },
    { id: "f_26", type: "multi", label: "Have the RAMS been agreed with the Main Contractor / Customer?", required: true, options: ["Yes", "No - RAMS to be approved at least 7 days prior to Rock Roofing starting on site. If no response, RAMS deemed to be accepted. "] },
    { id: "f_27", type: "longtext", label: "When have site inductions been agreed to be carried out?", required: true },
    { id: "s_28", type: "section", label: "Any other comments?" },
    { id: "f_29", type: "longtext", label: "Any other comments?" },
    { id: "s_30", type: "section", label: "Additional Confirmations and Requirements" },
    { id: "f_31", type: "note", label: "*Unless otherwise agreed, site power is required to be 110V (If supplied by a generator, a minimum 6KVA is needed)." },
    { id: "f_32", type: "note", label: "*Prior to our arrival on site, the roof / works areas must be clear of all materials, waste, debris and be prepared ready for the installation of our roof / cladding system. Any additional clearing, preparing or removal works required to be carried out by Rock Roofing Ltd will be charged at the hourly rate for a qualified installer as laid out in the Sub-Contract. If no hourly rate has been included in the contract, a charge of £43.35/hr will be applied." },
    { id: "f_33", type: "note", label: "*Unless otherwise agreed, easy parking is expected to be on site or within a maximum 200m from the site entrance with offloading of tools and equipment permitted inside the site entrance at a suitable laydown location." },
    { id: "f_34", type: "note", label: "*Adequate access routes through site are required to the location of our works." },
    { id: "f_35", type: "note", label: "*If mechanical offloading and lifting is being provided by others, the above delivery information should be considered, and adequate time set aside for our use of mechanical plant." },
    { id: "f_36", type: "note", label: "*Following this confirmation of the start date above, please make us aware of any changes at the earliest opportunity to mitigate disruption and incurred costs. Any changes required should be reported to Rock Roofing Ltd with a minimum of 7 clear days notice prior to the confirmed start date. Should changes be made after this time, Rock Roofing Ltd will seek to recover all costs incurred such as; lost productivity of labour, travel costs & accommodation costs. Following said change to the start date, the commencement period will reset and the period stated in the contract will apply to the newly requested date." },
    { id: "f_37", type: "note", label: "Until the works are complete and handed over, Rock Roofing Ltd are not liable for any damage and disruption to the structure or it's internals that may occur due to water ingress." },
  ],
}
export const SEED_FORMS = [
  dailySiteDiary,
  dailyQualityInspection,
  waterIngress,
  worksAreaHandover,
  startOnSite,
  preStart,
  internalHSAudit,
  ideasSuggestions,
]

export default SEED_FORMS
